apiVersion: v1
kind: ConfigMap
metadata:
  name: devtask-config
  namespace: devtask
data:
  MYSQL_HOST:     "mysql"
  MYSQL_PORT:     "3306"
  MYSQL_DATABASE: "devtask_db"
  MYSQL_USER:     "devtask"
  KAFKA_BROKERS:  "kafka:9092"
  REDIS_HOST:     "redis"
  REDIS_PORT:     "6379"
  LOG_LEVEL:      "info"
  JWT_EXPIRES_IN: "24h"
  AUTH_SERVICE_URL:         "http://auth-service:3001"
  TASK_SERVICE_URL:         "http://task-service:3002"
  NOTIFICATION_SERVICE_URL: "http://notification-service:3003"
