apiVersion: v1
kind: Secret
metadata:
  name: devtask-secrets
  namespace: devtask
type: Opaque
stringData:
  MYSQL_PASSWORD:      "devtask_password"
  MYSQL_ROOT_PASSWORD: "root_password"
  JWT_SECRET:          "supersecret_change_in_production"
